
export const CURR_CONVO_FAIL = "CURR_CONVO_FAIL";
export const CURR_CONVO_REQUEST = "CURR_CONVO_REQUEST";
export const CURR_CONVO_SUCCESS = "CURR_CONVO_SUCCESS";

export const ALL_CONVOS_FAIL = "ALL_CONVOS_FAIL";
export const ALL_CONVOS_REQUEST = "ALL_CONVOS_REQUEST";
export const ALL_CONVOS_SUCCESS = "ALL_CONVOS_SUCCESS";


export const CLEAR_ERRORS = "CLEAR_ERRORS";