
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";

export const SEND_MESSAGES_FAIL = "SEND_MESSAGES_FAIL";
export const SEND_MESSAGES_REQUEST = "SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";